inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - vendor/**/*

Naming/FileName:
  Exclude:
    - 'lib/dartsass-sprockets.rb'
