inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/dartsass-sprockets.rb'

Style/HashSyntax:
  EnforcedShorthandSyntax: never
